# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20170318_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates_x',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates_y',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
