# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20170408_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
