# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20170409_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='credibility',
            field=models.DecimalField(decimal_places=18, default=0.0, max_digits=20),
        ),
    ]
