# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_credibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(default='http://4.bp.blogspot.com/-ZoL4BRpPhkw/U6wnup4_6gI/AAAAAAAAACA/sKpM61pmJPo/s1600/no_pic_available.jpg', upload_to=''),
        ),
    ]
