# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_location_credibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='credibility',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
