# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_location_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(default='civic-map/static/no-image-icon-23485.png', upload_to=''),
        ),
    ]
